name: ZAP Baseline Scan - Simples (com Debug)

on:
  workflow_dispatch:

jobs:
  zap_scan:
    name: Run ZAP Simple Scan
    runs-on: ubuntu-latest
   
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: ZAP Baseline Scan (Alvo Simples)
        # Damos um 'id' a esta etapa para que possamos checá-la depois
        id: zap_scan_step
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://testphp.vulnweb.com/'
          fail_action: false # Mantemos false para o debug
          report_sarif: 'zap-results.sarif'

      # ================================================================
      # NOVA ETAPA DE DEPURAÇÃO:
      # Vamos listar todos os arquivos no diretório de trabalho.
      # Isso nos mostrará 100% se o 'zap-results.sarif' foi criado ou não.
      # ================================================================
      - name: List files in workspace
        if: always() # Sempre rode esta etapa, mesmo se o ZAP falhou
        run: |
          echo "Listando arquivos no diretório de trabalho:"
          ls -laR

      # Etapa de Upload
      - name: Upload SARIF to GitHub Security Tab
        if: always() # Mantemos always() por enquanto
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'zap-results.sarif'
