# Nome do fluxo: Teste de Integridade do Pipeline ZAP
name: ZAP Pipeline Integrity Test

on:
  workflow_dispatch: # Gatilho manual

jobs:
  zap_pipeline_test:
    name: Run ZAP Scan (on Example.com)
    runs-on: ubuntu-latest
   
    # Permissões são cruciais para a aba "Security"
    permissions:
      contents: read
      security-events: write

    steps:
      # Checkout é necessário
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ação de Scan com o conversor embutido
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          # ===============================================
          # A MUDANÇA CRÍTICA:
          # Usando um alvo 100% estável para testar o pipeline
          # ===============================================
          target: 'http://example.com'

          # O nome do arquivo SARIF que a action vai gerar
          sarif_file: 'zap-results.sarif'
         
          # IMPORTANTE:
          # Vamos dizer ao ZAP para não falhar o build,
          # pois 'example.com' não é vulnerável.
          # Nosso objetivo é testar a INTEGRAÇÃO.
          cmd_options: '-I'

      # Etapa de Upload
      # Se o passo anterior funcionar, este arquivo EXISTIRÁ.
      - name: Upload SARIF to GitHub Security Tab
        if: always() # Sempre tentar o upload
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'zap-results.sarif'
