name: OWASP ZAP Baseline Scan

on:
  push:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run OWASP ZAP Baseline scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://juice-shop.herokuapp.com' # Substitua pela URL do seu site
          # rules_file_name: '.zap/rules.tsv' # Opcional: para ignorar alertas
          # cmd_options: '-a' # Opcional: para adicionar mais opções de linha de comando
